package reporting

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/byteoverride/desynctrace/internal/detectors"
	"github.com/fatih/color"
	"github.com/jedib0t/go-pretty/v6/table"
)

type Report struct {
	Target      string                       `json:"target"`
	StartTime   time.Time                    `json:"start_time"`
	Duration    string                       `json:"duration"`
	Fingerprint string                       `json:"fingerprint"`
	Findings    []*detectors.DetectionResult `json:"findings"`
	Summary     ReportSummary                `json:"summary"`
}

type ReportSummary struct {
	TotalVectorsTested int `json:"total_vectors_tested"`
	VulnerabilitiesFound int `json:"vulnerabilities_found"`
	Confirmed          int `json:"confirmed"`
	HighConfidence     int `json:"high_confidence"`
}

func NewReport(target string) *Report {
	return &Report{
		Target:    target,
		StartTime: time.Now(),
		Findings:  []*detectors.DetectionResult{},
	}
}

func (r *Report) AddFinding(finding *detectors.DetectionResult) {
	r.Findings = append(r.Findings, finding)
}

func (r *Report) computeSummary() {
	r.Summary.VulnerabilitiesFound = 0
	r.Summary.Confirmed = 0
	r.Summary.HighConfidence = 0

	// Deduplicate by vector type — take highest confidence per type
	seen := make(map[string]*detectors.DetectionResult)
	for _, f := range r.Findings {
		if !f.IsVulnerable {
			continue
		}
		key := string(f.Vector) + "-" + f.Technique
		existing, ok := seen[key]
		if !ok || f.Confidence > existing.Confidence {
			seen[key] = f
		}
	}

	for _, f := range seen {
		r.Summary.VulnerabilitiesFound++
		if f.Confirmed {
			r.Summary.Confirmed++
		}
		if f.Confidence >= 80 {
			r.Summary.HighConfidence++
		}
	}
}

func (r *Report) GenerateJSON() ([]byte, error) {
	r.computeSummary()
	return json.MarshalIndent(r, "", "  ")
}

func (r *Report) SaveToFile(filename string) error {
	data, err := r.GenerateJSON()
	if err != nil {
		return err
	}
	return os.WriteFile(filename, data, 0644)
}

func (r *Report) SaveMarkdown(filename string) error {
	r.computeSummary()

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# DesyncTrace Scan Report\n\n"))
	sb.WriteString(fmt.Sprintf("**Target:** `%s`\n\n", r.Target))
	sb.WriteString(fmt.Sprintf("**Date:** %s\n\n", r.StartTime.Format(time.RFC3339)))
	sb.WriteString(fmt.Sprintf("**Duration:** %s\n\n", r.Duration))

	if r.Fingerprint != "" {
		sb.WriteString(fmt.Sprintf("**Fingerprint:** %s\n\n", r.Fingerprint))
	}

	sb.WriteString("## Summary\n\n")
	sb.WriteString(fmt.Sprintf("| Metric | Value |\n"))
	sb.WriteString(fmt.Sprintf("|--------|-------|\n"))
	sb.WriteString(fmt.Sprintf("| Vulnerabilities Found | %d |\n", r.Summary.VulnerabilitiesFound))
	sb.WriteString(fmt.Sprintf("| Confirmed (Poisoning) | %d |\n", r.Summary.Confirmed))
	sb.WriteString(fmt.Sprintf("| High Confidence (>80%%) | %d |\n", r.Summary.HighConfidence))
	sb.WriteString("\n")

	if len(r.Findings) == 0 {
		sb.WriteString("No vulnerabilities found.\n")
	} else {
		sb.WriteString("## Findings\n\n")

		// Group by vector
		grouped := make(map[string][]*detectors.DetectionResult)
		for _, f := range r.Findings {
			if f.IsVulnerable {
				grouped[string(f.Vector)] = append(grouped[string(f.Vector)], f)
			}
		}

		for vector, findings := range grouped {
			sb.WriteString(fmt.Sprintf("### %s\n\n", vector))
			for _, f := range findings {
				confirmedStr := ""
				if f.Confirmed {
					confirmedStr = " **CONFIRMED**"
				}
				sb.WriteString(fmt.Sprintf("- **Confidence:** %d%%%s\n", f.Confidence, confirmedStr))
				sb.WriteString(fmt.Sprintf("  - **Technique:** %s\n", f.Technique))
				sb.WriteString(fmt.Sprintf("  - **Evidence:** %s\n", f.Evidence))
				if f.Attempts > 0 {
					sb.WriteString(fmt.Sprintf("  - **Success Rate:** %d/%d attempts\n", f.Successes, f.Attempts))
				}
				sb.WriteString("\n")
			}
		}
	}

	sb.WriteString("\n---\n*Generated by DesyncTrace*\n")
	return os.WriteFile(filename, []byte(sb.String()), 0644)
}

func (r *Report) SaveText(filename string) error {
	r.computeSummary()

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("DesyncTrace Scan Report\n"))
	sb.WriteString(fmt.Sprintf("========================\n"))
	sb.WriteString(fmt.Sprintf("Target: %s\n", r.Target))
	sb.WriteString(fmt.Sprintf("Date: %s\n", r.StartTime.Format(time.RFC3339)))
	sb.WriteString(fmt.Sprintf("Duration: %s\n", r.Duration))
	if r.Fingerprint != "" {
		sb.WriteString(fmt.Sprintf("Fingerprint: %s\n", r.Fingerprint))
	}
	sb.WriteString(fmt.Sprintf("\nVulnerabilities: %d (Confirmed: %d)\n\n",
		r.Summary.VulnerabilitiesFound, r.Summary.Confirmed))

	for _, f := range r.Findings {
		if !f.IsVulnerable {
			continue
		}
		confirmed := ""
		if f.Confirmed {
			confirmed = " [CONFIRMED]"
		}
		sb.WriteString(fmt.Sprintf("[%s] Confidence: %d%%%s\n", f.Vector, f.Confidence, confirmed))
		sb.WriteString(fmt.Sprintf("  Technique: %s\n", f.Technique))
		sb.WriteString(fmt.Sprintf("  Evidence: %s\n\n", f.Evidence))
	}

	return os.WriteFile(filename, []byte(sb.String()), 0644)
}

func (r *Report) PrintSummary() {
	r.computeSummary()

	bold := color.New(color.FgCyan, color.Bold)
	bold.Printf("\n DESYNCTRACE SCAN REPORT — %s\n", r.Target)
	fmt.Printf(" Duration: %s\n", r.Duration)
	if r.Fingerprint != "" {
		fmt.Printf(" Fingerprint: %s\n", r.Fingerprint)
	}
	fmt.Println()

	if len(r.Findings) == 0 {
		color.Green(" No vulnerabilities found.\n")
		fmt.Println("==================================================")
		return
	}

	t := table.NewWriter()
	t.SetOutputMirror(os.Stdout)
	t.SetStyle(table.StyleLight)
	t.AppendHeader(table.Row{"Vector", "Confidence", "Technique", "Status", "Evidence"})

	for _, f := range r.Findings {
		if !f.IsVulnerable {
			continue
		}

		status := color.YellowString("SUSPECTED")
		if f.Confirmed {
			status = color.RedString("CONFIRMED")
		}

		confStr := fmt.Sprintf("%d%%", f.Confidence)
		if f.Confidence >= 80 {
			confStr = color.RedString(confStr)
		} else if f.Confidence >= 60 {
			confStr = color.YellowString(confStr)
		}

		evidence := f.Evidence
		if len(evidence) > 80 {
			evidence = evidence[:77] + "..."
		}

		t.AppendRow(table.Row{
			color.RedString(string(f.Vector)),
			confStr,
			f.Technique,
			status,
			evidence,
		})
	}
	t.Render()

	// Summary line
	fmt.Println()
	if r.Summary.Confirmed > 0 {
		color.Red(" %d CONFIRMED vulnerabilities found!", r.Summary.Confirmed)
	}
	if r.Summary.VulnerabilitiesFound > r.Summary.Confirmed {
		color.Yellow(" %d suspected (timing-based) findings — run without --safe to confirm.",
			r.Summary.VulnerabilitiesFound-r.Summary.Confirmed)
	}
	fmt.Println("==================================================")
}
